version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile-db
    networks:
      - altbot
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  bot:
    build:
      context: .
      dockerfile: Dockerfile-bot
    networks:
      - altbot
    depends_on:
      - db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DISCORD_PREFIX=${prefix}
      - DISCORD_APPID=${application_id}
      - DISCORD_OID=${owner_id}
      

volumes:
  pgdata:

networks:
  altbot:
    driver: bridge

